@hostname = localhost
@port = 3333
@suffix = api/v1
@fullPath = {{hostname}}:{{port}}/{{suffix}}


GET http://{{fullPath}}/users  HTTP/1.1

###

GET http://{{fullPath}}/users/61824eb37b61692921579c6b  HTTP/1.1

###

POST http://{{fullPath}}/users HTTP/1.1
content-type: application/json

{
    "name":"Adminuser",
    "email":"Zizo@me2.com",
    "passwordHash":"asdasd",
    "street":"",
    "apartment":"",
    "city":"",
    "zip":"",
    "country":"",
    "phone":"",
    "isAdmin":false
}
    
###
