@hostname = localhost
@port = 3333/
@suffix = api/v1
@fullPath = {{hostname}}:{{port}}{{suffix}}


GET http://{{fullPath}}/products  HTTP/1.1

###

GET http://{{fullPath}}/categories  HTTP/1.1

### 
POST http://localhost:3333/api/v1/products HTTP/1.1
content-type: application/json

{
    "name":"From Rest client",
    "description":"aasdsad sdaaaa",
    "richDescription":"adsasd ",
    "brand":"asdas",
    "category":"61680cc3262d5a8bf9defe52",
    "price":"223",
    "numReviews":"213",
    "isFeatured":"true",
    "image":"33.png",
    "countInStock":123,
    "rating":"3"
}

    ###

GET  http://{{fullPath}}/products/617e91460411e79322fc415e HTTP/1.1

###